### ISSUE TITLE
Instagram does not download








### ISSUE THREAD

**Issue by shiaooar** [teamezra/ezrayt-dl#2]
Perfect

**Comment by Shiaofanh** [comment]
It appears that directory '~/storage' already exists.   This script is going to rebuild its structure from      scratch, wiping all dangling files. The actual storage  content IS NOT going to be deleted.                                                                             Do you want to continue? (y/n) y                                                                                 Please Wait ...                                        mkdir: cannot create directory ‘/data/data/com.termux/files/home/storage/shared/YouTube-DL’: File exists        mkdir: cannot create directory ‘/data/data/com.termux/files/home/bin’: File exists                              --2022-01-15 14:42:22--  https://pastebin.com/raw/dqBrGtRP                                                      Resolving pastebin.com... 104.23.99.190, 104.23.98.190, 2606:4700:10::6817:62be, ...                            Connecting to pastebin.com|104.23.99.190|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/plain]                        Saving to: ‘/data/data/com.termux/files/home/bin/termux-url-opener’                                             
/data/data/co        2.58K  --.-KB/s    in 0s                                                                   2022-01-15 14:42:24 (17.2 MB/s) - ‘/data/data/com.termux/files/home/bin/termux-url-opener’ saved [2647]

dos2unix: converting file /data/data/com.termux/files/home/bin/termux-url-opener to Unix format...

 Ezra Yt-downloader Setup Complete, Enjoy!

~/ezrayt-dl $
