### ISSUE TITLE
Instagram


### ISSUE THREAD

**Issue by shiaooar** [teamezra/ezrayt-dl#3]
Fixed

**Comment by Shiaofanh** [comment]
Trying to Download ...
WARNING: [Instagram] parsing .netrc: [Errno 2] No such file or directory: '/data/data/com.termux/files/home/.netrc'
[Instagram] CYvCEVTpJS5: Downloading webpage
WARNING: [Instagram] Main webpage is locked behind the login page. Retrying with embed webpage (Note that some metadata might be missing)
[Instagram] CYvCEVTpJS5: Downloading embed webpage
ERROR: [Instagram] CYvCEVTpJS5: Requested format is not available

 File saved here: storage/shared/☣Ezra⸸Youtube-DL✡
^C
[Process completed (signal 2) - press Enter]

**Comment by shiaooar** [comment]
Let me try.Thanks
