### ISSUE TITLE
Screenshot (Jan 17, 2022 4:12:54 PM)

### ISSUE THREAD

**Issue by shiaooar** [teamezra/ezrayt-dl#5]
Termux-url-opene
WARNING: [youtube] parsing .netrc: [Errno 2] No such file or directory: '/data/data/com.termux/files/home/.netrc'
[youtube] ZqhiQEqkbTc: Downloading webpage
WARNING: [youtube] Unable to download webpage: <urlopen error [Errno 7] No address associated with hostname>
[youtube] ZqhiQEqkbTc: Downloading android player API JSON

**Comment by teamezra** [comment]
Explain

**Comment by shiaooar** [comment]
ed.
HTTP request sent, awaiting response... 200 OK          Length: unspecified [text/plain]                        Saving to: ‘/data/data/com.termux/files/home/bin/termux-url-opener’

**Comment by shiaooar** [comment]
Setting Up Storage ...

 Please Allow Storage Access!

It appears that directory '~/storage' already exists.   This script is
going to rebuild its structure from
scratch, wiping all dangling files. The actual storage
content IS NOT going to be deleted.

Do you want to continue? (y/n) y

 Please Wait ...                                        mkdir: cannot
create directory
‘/data/data/com.termux/files/home/storage/shared/YouTube-DL’: File exists
      mkdir: cannot create directory
‘/data/data/com.termux/files/home/bin’: File exists
--2022-01-17 16:20:20--  https://pastebin.com/raw/dqBrGtRP
                                    Resolving pastebin.com...
104.23.98.190, 104.23.99.190, 2606:4700:10::6817:62be, ...
          Connecting to pastebin.com|104.23.98.190|:443... connected.
HTTP request sent, awaiting response... 200 OK          Length: unspecified
[text/plain]                        Saving to:
‘/data/data/com.termux/files/home/bin/termux-url-opener’

/data/data/co        2.58K  --.-KB/s    in 0s
                                     2022-01-17 16:20:26 (23.6 MB/s) -
‘/data/data/com.termux/files/home/bin/termux-url-opener’ saved [2647]
